spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloContact?characterEncoding=UTF-8&serverTimezone=UTC
    username: helloContact
    password: helloContact
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true

  redis:
    host: localhost
    port: 6379

  cache:
    redis:
      time-to-live: 1200000
    type: redis